name: Dispatch Submodule Update

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_PRIVATE_KEY }}
          owner: bcgov-c
          repositories: |
            mfin-airflow-poc
      - name: Trigger repository_dispatch
        id: trigger_dispatch
        run: |
          status_code=$(curl -w "%{http_code}" -o /dev/null -s -X POST https://api.github.com/repos/bcgov-c/mfin-airflow-poc/dispatches \
            -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event_type":"submodule_update"}')
          echo "status_code=$status_code" >> $GITHUB_OUTPUT

      - name: Log curl HTTP status code
        run: |
          echo "Repository dispatch curl returned HTTP status code: ${{ steps.trigger_dispatch.outputs.status_code }}"